"""empty message

Revision ID: 0c973c1894d1
Revises: 79c474ec4c9d
Create Date: 2019-02-06 22:13:10.405188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c973c1894d1'
down_revision = '79c474ec4c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('id', sa.Integer(), autoincrement=True, nullable=True))
    op.create_index(op.f('ix_player_id'), 'player', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_id'), table_name='player')
    op.drop_column('player', 'id')
    # ### end Alembic commands ###

