"""empty message

Revision ID: 16165a67d6a4
Revises: 79c474ec4c9d
Create Date: 2019-02-16 17:06:48.807309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16165a67d6a4'
down_revision = '79c474ec4c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_player_created_date'), 'player', ['created_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_created_date'), table_name='player')
    op.drop_column('player', 'created_date')
    # ### end Alembic commands ###
