"""empty message

Revision ID: 67577929bcde
Revises: e71b9fe8fae0
Create Date: 2019-04-12 10:32:09.505386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67577929bcde'
down_revision = 'e71b9fe8fae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TeamFines')
    op.add_column('fine', sa.Column('team_uuid', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'fine', 'team', ['team_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fine', type_='foreignkey')
    op.drop_column('fine', 'team_uuid')
    op.create_table('TeamFines',
    sa.Column('team_uuid', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('fine_uuid', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fine_uuid'], ['fine.uuid'], name='TeamFines_fine_uuid_fkey'),
    sa.ForeignKeyConstraint(['team_uuid'], ['team.uuid'], name='TeamFines_team_uuid_fkey')
    )
    # ### end Alembic commands ###
