"""empty message

Revision ID: e71b9fe8fae0
Revises: 16165a67d6a4
Create Date: 2019-04-11 17:20:53.959060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e71b9fe8fae0'
down_revision = '16165a67d6a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fine', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_fine_created_date'), 'fine', ['created_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fine_created_date'), table_name='fine')
    op.drop_column('fine', 'created_date')
    # ### end Alembic commands ###
